import type { Resource } from '@/services/api/teacher/types/modelType'

type ResourceWithCollection = Resource & { collectionId: string }

export const resourcesMock: Array<ResourceWithCollection> = [
  {
    id: 1,
    collectionId: crypto.randomUUID(),
    fileName: 'Chapter 4 - Algebra Basics.pdf',
    type: 'pdf',
    dateAdded: 'Oct 24, 2023',
    size: '2.4 MB',
  },
  {
    id: 2,
    collectionId: crypto.randomUUID(),
    fileName: 'Mid-Term Review Notes.docx',
    type: 'docx',
    dateAdded: 'Oct 22, 2023',
    size: '450 KB',
  },
  {
    id: 3,
    collectionId: crypto.randomUUID(),
    fileName: 'Student Scores Data.xlsx',
    type: 'xlsx',
    dateAdded: 'Oct 21, 2023',
    size: '1.2 MB',
  },
  {
    id: 4,
    collectionId: crypto.randomUUID(),
    fileName: 'Diagram_Trigonometry.png',
    type: 'png',
    dateAdded: 'Oct 20, 2023',
    size: '3.1 MB',
  },
  {
    id: 5,
    collectionId: crypto.randomUUID(),
    fileName: 'Practice Exam - Set A.pdf',
    type: 'pdf',
    dateAdded: 'Oct 18, 2023',
    size: '1.8 MB',
  },
  {
    id: 6,
    collectionId: crypto.randomUUID(),
    fileName: 'Supplementary_Materials.zip',
    type: 'zip',
    dateAdded: 'Oct 15, 2023',
    size: '5.4 MB',
  },
  {
    id: 7,
    collectionId: crypto.randomUUID(),
    fileName: 'Additional Notes.pdf',
    type: 'pdf',
    dateAdded: 'Oct 14, 2023',
    size: '1.1 MB',
  },
  {
    id: 8,
    collectionId: crypto.randomUUID(),
    fileName: 'Graphing_Calculator_Guide.pdf',
    type: 'pdf',
    dateAdded: 'Oct 13, 2023',
    size: '2.7 MB',
  },
  {
    id: 9,
    collectionId: crypto.randomUUID(),
    fileName: 'Formula_Sheet.docx',
    type: 'docx',
    dateAdded: 'Oct 12, 2023',
    size: '300 KB',
  },
  {
    id: 10,
    collectionId: crypto.randomUUID(),
    fileName: 'Lesson Plan - Week 6.pptx',
    type: 'pptx',
    dateAdded: 'Oct 11, 2023',
    size: '4.2 MB',
  },
  {
    id: 11,
    collectionId: crypto.randomUUID(),
    fileName: 'Physics Lab Instructions.pdf',
    type: 'pdf',
    dateAdded: 'Nov 03, 2023',
    size: '1.6 MB',
  },
  {
    id: 12,
    collectionId: crypto.randomUUID(),
    fileName: 'Wave Motion Worksheet.docx',
    type: 'docx',
    dateAdded: 'Nov 01, 2023',
    size: '520 KB',
  },
  {
    id: 13,
    collectionId: crypto.randomUUID(),
    fileName: 'Lab Results Template.xlsx',
    type: 'xlsx',
    dateAdded: 'Oct 30, 2023',
    size: '860 KB',
  },
  {
    id: 14,
    collectionId: crypto.randomUUID(),
    fileName: 'Projectile_Motion_Demo.mp4',
    type: 'mp4',
    dateAdded: 'Oct 29, 2023',
    size: '18.3 MB',
  },
  {
    id: 15,
    collectionId: crypto.randomUUID(),
    fileName: 'Chemistry Safety Rules.pdf',
    type: 'pdf',
    dateAdded: 'Sep 24, 2023',
    size: '980 KB',
  },
  {
    id: 16,
    collectionId: crypto.randomUUID(),
    fileName: 'Organic Compounds Overview.pptx',
    type: 'pptx',
    dateAdded: 'Sep 22, 2023',
    size: '6.1 MB',
  },
  {
    id: 17,
    collectionId: crypto.randomUUID(),
    fileName: 'Periodic Table (Printable).png',
    type: 'png',
    dateAdded: 'Sep 20, 2023',
    size: '2.2 MB',
  },
  {
    id: 18,
    collectionId: crypto.randomUUID(),
    fileName: 'Exam Prep Bundle.zip',
    type: 'zip',
    dateAdded: 'Sep 18, 2023',
    size: '9.7 MB',
  },
]
