"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _route_teacher_classes from './route-teacher-classes.bones.json'
import _teacher_classes_page from './teacher-classes-page.bones.json'
import _teacher_classes_send_resource from './teacher-classes-send-resource.bones.json'
import _teacher_classes_collections_grid from './teacher-classes-collections-grid.bones.json'
import _teacher_layout from './teacher-layout.bones.json'
import _resources_table from './resources-table.bones.json'
import _route_teacher_settings from './route-teacher-settings.bones.json'
import _route_teacher_notifications from './route-teacher-notifications.bones.json'
import _teacher_notifications_page from './teacher-notifications-page.bones.json'
import _route_teacher_classes_allcollections from './route-teacher-classes-allcollections.bones.json'
import _teacher_collections_page from './teacher-collections-page.bones.json'
import _teacher_collections_grid from './teacher-collections-grid.bones.json'
import _route_teacher_classes_id from './route-teacher-classes-id.bones.json'
import _teacher_class_folder_page from './teacher-class-folder-page.bones.json'
import _teacher_class_folder_detail from './teacher-class-folder-detail.bones.json'
import _route_teacher_classes_d3a7f5c6_8e4f_6f7a_0c1d_2b3c4d5e6f7a from './route-teacher-classes-d3a7f5c6-8e4f-6f7a-0c1d-2b3c4d5e6f7a.bones.json'

registerBones({
  "route-teacher-classes": _route_teacher_classes,
  "teacher-classes-page": _teacher_classes_page,
  "teacher-classes-send-resource": _teacher_classes_send_resource,
  "teacher-classes-collections-grid": _teacher_classes_collections_grid,
  "teacher-layout": _teacher_layout,
  "resources-table": _resources_table,
  "route-teacher-settings": _route_teacher_settings,
  "route-teacher-notifications": _route_teacher_notifications,
  "teacher-notifications-page": _teacher_notifications_page,
  "route-teacher-classes-allcollections": _route_teacher_classes_allcollections,
  "teacher-collections-page": _teacher_collections_page,
  "teacher-collections-grid": _teacher_collections_grid,
  "route-teacher-classes-id": _route_teacher_classes_id,
  "teacher-class-folder-page": _teacher_class_folder_page,
  "teacher-class-folder-detail": _teacher_class_folder_detail,
  "route-teacher-classes-d3a7f5c6-8e4f-6f7a-0c1d-2b3c4d5e6f7a": _route_teacher_classes_d3a7f5c6_8e4f_6f7a_0c1d_2b3c4d5e6f7a,
})
