/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher/settings'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerAnnouncementsRouteImport } from './routes/owner/announcements'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TeacherSubjectsIndexRouteImport } from './routes/teacher/subjects/index'
import { Route as TeacherNotificationsIndexRouteImport } from './routes/teacher/notifications/index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher/classes/index'
import { Route as StudentSubjectsIndexRouteImport } from './routes/student/subjects.index'
import { Route as StudentNotificationIndexRouteImport } from './routes/student/notification/index'
import { Route as OwnerTeachersIndexRouteImport } from './routes/owner/teachers/index'
import { Route as OwnerStudentsIndexRouteImport } from './routes/owner/students/index'
import { Route as OwnerGradesIndexRouteImport } from './routes/owner/grades/index'
import { Route as TeacherSubjectsSubjectCodeRouteImport } from './routes/teacher/subjects/$subjectCode'
import { Route as TeacherNotificationsAddRouteImport } from './routes/teacher/notifications/add'
import { Route as TeacherNotificationsNotificationIdRouteImport } from './routes/teacher/notifications/$notificationId'
import { Route as TeacherMarksClassIdRouteImport } from './routes/teacher/marks/$classId'
import { Route as TeacherClassesAllCollectionsRouteImport } from './routes/teacher/classes/allCollections'
import { Route as TeacherClassesFolderIdRouteImport } from './routes/teacher/classes/$folderId'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher/classes/$classId'
import { Route as TeacherAttendanceClassIdRouteImport } from './routes/teacher/attendance/$classId'
import { Route as StudentSubjectsSubjectCodeRouteImport } from './routes/student/subjects.$subjectCode'
import { Route as StudentNotificationNotificationIdRouteImport } from './routes/student/notification/$notificationId'
import { Route as OwnerTeachersAddRouteImport } from './routes/owner/teachers/add'
import { Route as OwnerStudentsAddRouteImport } from './routes/owner/students/add'
import { Route as OwnerStudentsStudentIdRouteImport } from './routes/owner/students/$studentId'
import { Route as OwnerGradesNameRouteImport } from './routes/owner/grades/$name'
import { Route as OwnerTeachersTeacherIdIndexRouteImport } from './routes/owner/teachers/$teacherId/index'
import { Route as OwnerTeachersTeacherIdAssignementsRouteImport } from './routes/owner/teachers/$teacherId/assignements'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnnouncementsRoute = OwnerAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => OwnerRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubjectsIndexRoute = TeacherSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsIndexRoute =
  TeacherNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSubjectsIndexRoute = StudentSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationIndexRoute =
  StudentNotificationIndexRouteImport.update({
    id: '/notification/',
    path: '/notification/',
    getParentRoute: () => StudentRoute,
  } as any)
const OwnerTeachersIndexRoute = OwnerTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStudentsIndexRoute = OwnerStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGradesIndexRoute = OwnerGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => OwnerRoute,
} as any)
const TeacherSubjectsSubjectCodeRoute =
  TeacherSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherNotificationsAddRoute = TeacherNotificationsAddRouteImport.update({
  id: '/notifications/add',
  path: '/notifications/add',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsNotificationIdRoute =
  TeacherNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherMarksClassIdRoute = TeacherMarksClassIdRouteImport.update({
  id: '/marks/$classId',
  path: '/marks/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesAllCollectionsRoute =
  TeacherClassesAllCollectionsRouteImport.update({
    id: '/classes/allCollections',
    path: '/classes/allCollections',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassesFolderIdRoute = TeacherClassesFolderIdRouteImport.update({
  id: '/classes/$folderId',
  path: '/classes/$folderId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceClassIdRoute =
  TeacherAttendanceClassIdRouteImport.update({
    id: '/attendance/$classId',
    path: '/attendance/$classId',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentSubjectsSubjectCodeRoute =
  StudentSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentNotificationNotificationIdRoute =
  StudentNotificationNotificationIdRouteImport.update({
    id: '/notification/$notificationId',
    path: '/notification/$notificationId',
    getParentRoute: () => StudentRoute,
  } as any)
const OwnerTeachersAddRoute = OwnerTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStudentsAddRoute = OwnerStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStudentsStudentIdRoute = OwnerStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGradesNameRoute = OwnerGradesNameRouteImport.update({
  id: '/grades/$name',
  path: '/grades/$name',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTeachersTeacherIdIndexRoute =
  OwnerTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerTeachersTeacherIdAssignementsRoute =
  OwnerTeachersTeacherIdAssignementsRouteImport.update({
    id: '/teachers/$teacherId/assignements',
    path: '/teachers/$teacherId/assignements',
    getParentRoute: () => OwnerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/grades/$name': typeof OwnerGradesNameRoute
  '/owner/students/$studentId': typeof OwnerStudentsStudentIdRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/owner/grades/': typeof OwnerGradesIndexRoute
  '/owner/students/': typeof OwnerStudentsIndexRoute
  '/owner/teachers/': typeof OwnerTeachersIndexRoute
  '/student/notification/': typeof StudentNotificationIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/notifications/': typeof TeacherNotificationsIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/owner/teachers/$teacherId/assignements': typeof OwnerTeachersTeacherIdAssignementsRoute
  '/owner/teachers/$teacherId/': typeof OwnerTeachersTeacherIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/grades/$name': typeof OwnerGradesNameRoute
  '/owner/students/$studentId': typeof OwnerStudentsStudentIdRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/owner/grades': typeof OwnerGradesIndexRoute
  '/owner/students': typeof OwnerStudentsIndexRoute
  '/owner/teachers': typeof OwnerTeachersIndexRoute
  '/student/notification': typeof StudentNotificationIndexRoute
  '/student/subjects': typeof StudentSubjectsIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/notifications': typeof TeacherNotificationsIndexRoute
  '/teacher/subjects': typeof TeacherSubjectsIndexRoute
  '/owner/teachers/$teacherId/assignements': typeof OwnerTeachersTeacherIdAssignementsRoute
  '/owner/teachers/$teacherId': typeof OwnerTeachersTeacherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/owner/announcements': typeof OwnerAnnouncementsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/owner/grades/$name': typeof OwnerGradesNameRoute
  '/owner/students/$studentId': typeof OwnerStudentsStudentIdRoute
  '/owner/students/add': typeof OwnerStudentsAddRoute
  '/owner/teachers/add': typeof OwnerTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/classes/$folderId': typeof TeacherClassesFolderIdRoute
  '/teacher/classes/allCollections': typeof TeacherClassesAllCollectionsRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/notifications/$notificationId': typeof TeacherNotificationsNotificationIdRoute
  '/teacher/notifications/add': typeof TeacherNotificationsAddRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/owner/grades/': typeof OwnerGradesIndexRoute
  '/owner/students/': typeof OwnerStudentsIndexRoute
  '/owner/teachers/': typeof OwnerTeachersIndexRoute
  '/student/notification/': typeof StudentNotificationIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/notifications/': typeof TeacherNotificationsIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/owner/teachers/$teacherId/assignements': typeof OwnerTeachersTeacherIdAssignementsRoute
  '/owner/teachers/$teacherId/': typeof OwnerTeachersTeacherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/auth/login'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/grades/$name'
    | '/owner/students/$studentId'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/marks/$classId'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/teacher/subjects/$subjectCode'
    | '/owner/grades/'
    | '/owner/students/'
    | '/owner/teachers/'
    | '/student/notification/'
    | '/student/subjects/'
    | '/teacher/classes/'
    | '/teacher/notifications/'
    | '/teacher/subjects/'
    | '/owner/teachers/$teacherId/assignements'
    | '/owner/teachers/$teacherId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/auth/login'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/grades/$name'
    | '/owner/students/$studentId'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/marks/$classId'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/teacher/subjects/$subjectCode'
    | '/owner/grades'
    | '/owner/students'
    | '/owner/teachers'
    | '/student/notification'
    | '/student/subjects'
    | '/teacher/classes'
    | '/teacher/notifications'
    | '/teacher/subjects'
    | '/owner/teachers/$teacherId/assignements'
    | '/owner/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/auth/login'
    | '/owner/announcements'
    | '/owner/dashboard'
    | '/owner/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/owner/grades/$name'
    | '/owner/students/$studentId'
    | '/owner/students/add'
    | '/owner/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/$folderId'
    | '/teacher/classes/allCollections'
    | '/teacher/marks/$classId'
    | '/teacher/notifications/$notificationId'
    | '/teacher/notifications/add'
    | '/teacher/subjects/$subjectCode'
    | '/owner/grades/'
    | '/owner/students/'
    | '/owner/teachers/'
    | '/student/notification/'
    | '/student/subjects/'
    | '/teacher/classes/'
    | '/teacher/notifications/'
    | '/teacher/subjects/'
    | '/owner/teachers/$teacherId/assignements'
    | '/owner/teachers/$teacherId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/announcements': {
      id: '/owner/announcements'
      path: '/announcements'
      fullPath: '/owner/announcements'
      preLoaderRoute: typeof OwnerAnnouncementsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/subjects/': {
      id: '/teacher/subjects/'
      path: '/subjects'
      fullPath: '/teacher/subjects/'
      preLoaderRoute: typeof TeacherSubjectsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications/': {
      id: '/teacher/notifications/'
      path: '/notifications'
      fullPath: '/teacher/notifications/'
      preLoaderRoute: typeof TeacherNotificationsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/subjects/': {
      id: '/student/subjects/'
      path: '/subjects'
      fullPath: '/student/subjects/'
      preLoaderRoute: typeof StudentSubjectsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification/': {
      id: '/student/notification/'
      path: '/notification'
      fullPath: '/student/notification/'
      preLoaderRoute: typeof StudentNotificationIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/owner/teachers/': {
      id: '/owner/teachers/'
      path: '/teachers'
      fullPath: '/owner/teachers/'
      preLoaderRoute: typeof OwnerTeachersIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/students/': {
      id: '/owner/students/'
      path: '/students'
      fullPath: '/owner/students/'
      preLoaderRoute: typeof OwnerStudentsIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/grades/': {
      id: '/owner/grades/'
      path: '/grades'
      fullPath: '/owner/grades/'
      preLoaderRoute: typeof OwnerGradesIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/teacher/subjects/$subjectCode': {
      id: '/teacher/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/teacher/subjects/$subjectCode'
      preLoaderRoute: typeof TeacherSubjectsSubjectCodeRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications/add': {
      id: '/teacher/notifications/add'
      path: '/notifications/add'
      fullPath: '/teacher/notifications/add'
      preLoaderRoute: typeof TeacherNotificationsAddRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications/$notificationId': {
      id: '/teacher/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/teacher/notifications/$notificationId'
      preLoaderRoute: typeof TeacherNotificationsNotificationIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/marks/$classId': {
      id: '/teacher/marks/$classId'
      path: '/marks/$classId'
      fullPath: '/teacher/marks/$classId'
      preLoaderRoute: typeof TeacherMarksClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/allCollections': {
      id: '/teacher/classes/allCollections'
      path: '/classes/allCollections'
      fullPath: '/teacher/classes/allCollections'
      preLoaderRoute: typeof TeacherClassesAllCollectionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$folderId': {
      id: '/teacher/classes/$folderId'
      path: '/classes/$folderId'
      fullPath: '/teacher/classes/$folderId'
      preLoaderRoute: typeof TeacherClassesFolderIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance/$classId': {
      id: '/teacher/attendance/$classId'
      path: '/attendance/$classId'
      fullPath: '/teacher/attendance/$classId'
      preLoaderRoute: typeof TeacherAttendanceClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/subjects/$subjectCode': {
      id: '/student/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/student/subjects/$subjectCode'
      preLoaderRoute: typeof StudentSubjectsSubjectCodeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification/$notificationId': {
      id: '/student/notification/$notificationId'
      path: '/notification/$notificationId'
      fullPath: '/student/notification/$notificationId'
      preLoaderRoute: typeof StudentNotificationNotificationIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/owner/teachers/add': {
      id: '/owner/teachers/add'
      path: '/teachers/add'
      fullPath: '/owner/teachers/add'
      preLoaderRoute: typeof OwnerTeachersAddRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/students/add': {
      id: '/owner/students/add'
      path: '/students/add'
      fullPath: '/owner/students/add'
      preLoaderRoute: typeof OwnerStudentsAddRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/students/$studentId': {
      id: '/owner/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/owner/students/$studentId'
      preLoaderRoute: typeof OwnerStudentsStudentIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/grades/$name': {
      id: '/owner/grades/$name'
      path: '/grades/$name'
      fullPath: '/owner/grades/$name'
      preLoaderRoute: typeof OwnerGradesNameRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/teachers/$teacherId/': {
      id: '/owner/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/owner/teachers/$teacherId/'
      preLoaderRoute: typeof OwnerTeachersTeacherIdIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/teachers/$teacherId/assignements': {
      id: '/owner/teachers/$teacherId/assignements'
      path: '/teachers/$teacherId/assignements'
      fullPath: '/owner/teachers/$teacherId/assignements'
      preLoaderRoute: typeof OwnerTeachersTeacherIdAssignementsRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerAnnouncementsRoute: typeof OwnerAnnouncementsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerGradesNameRoute: typeof OwnerGradesNameRoute
  OwnerStudentsStudentIdRoute: typeof OwnerStudentsStudentIdRoute
  OwnerStudentsAddRoute: typeof OwnerStudentsAddRoute
  OwnerTeachersAddRoute: typeof OwnerTeachersAddRoute
  OwnerGradesIndexRoute: typeof OwnerGradesIndexRoute
  OwnerStudentsIndexRoute: typeof OwnerStudentsIndexRoute
  OwnerTeachersIndexRoute: typeof OwnerTeachersIndexRoute
  OwnerTeachersTeacherIdAssignementsRoute: typeof OwnerTeachersTeacherIdAssignementsRoute
  OwnerTeachersTeacherIdIndexRoute: typeof OwnerTeachersTeacherIdIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnnouncementsRoute: OwnerAnnouncementsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerGradesNameRoute: OwnerGradesNameRoute,
  OwnerStudentsStudentIdRoute: OwnerStudentsStudentIdRoute,
  OwnerStudentsAddRoute: OwnerStudentsAddRoute,
  OwnerTeachersAddRoute: OwnerTeachersAddRoute,
  OwnerGradesIndexRoute: OwnerGradesIndexRoute,
  OwnerStudentsIndexRoute: OwnerStudentsIndexRoute,
  OwnerTeachersIndexRoute: OwnerTeachersIndexRoute,
  OwnerTeachersTeacherIdAssignementsRoute:
    OwnerTeachersTeacherIdAssignementsRoute,
  OwnerTeachersTeacherIdIndexRoute: OwnerTeachersTeacherIdIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentNotificationNotificationIdRoute: typeof StudentNotificationNotificationIdRoute
  StudentSubjectsSubjectCodeRoute: typeof StudentSubjectsSubjectCodeRoute
  StudentNotificationIndexRoute: typeof StudentNotificationIndexRoute
  StudentSubjectsIndexRoute: typeof StudentSubjectsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentNotificationNotificationIdRoute:
    StudentNotificationNotificationIdRoute,
  StudentSubjectsSubjectCodeRoute: StudentSubjectsSubjectCodeRoute,
  StudentNotificationIndexRoute: StudentNotificationIndexRoute,
  StudentSubjectsIndexRoute: StudentSubjectsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherAttendanceClassIdRoute: typeof TeacherAttendanceClassIdRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherClassesFolderIdRoute: typeof TeacherClassesFolderIdRoute
  TeacherClassesAllCollectionsRoute: typeof TeacherClassesAllCollectionsRoute
  TeacherMarksClassIdRoute: typeof TeacherMarksClassIdRoute
  TeacherNotificationsNotificationIdRoute: typeof TeacherNotificationsNotificationIdRoute
  TeacherNotificationsAddRoute: typeof TeacherNotificationsAddRoute
  TeacherSubjectsSubjectCodeRoute: typeof TeacherSubjectsSubjectCodeRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherNotificationsIndexRoute: typeof TeacherNotificationsIndexRoute
  TeacherSubjectsIndexRoute: typeof TeacherSubjectsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherAttendanceClassIdRoute: TeacherAttendanceClassIdRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherClassesFolderIdRoute: TeacherClassesFolderIdRoute,
  TeacherClassesAllCollectionsRoute: TeacherClassesAllCollectionsRoute,
  TeacherMarksClassIdRoute: TeacherMarksClassIdRoute,
  TeacherNotificationsNotificationIdRoute:
    TeacherNotificationsNotificationIdRoute,
  TeacherNotificationsAddRoute: TeacherNotificationsAddRoute,
  TeacherSubjectsSubjectCodeRoute: TeacherSubjectsSubjectCodeRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherNotificationsIndexRoute: TeacherNotificationsIndexRoute,
  TeacherSubjectsIndexRoute: TeacherSubjectsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  SignUpRoute: SignUpRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
