/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher/settings'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentCalendarRouteImport } from './routes/student/calendar'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as PagesTermsRouteImport } from './routes/Pages/terms'
import { Route as PagesSecurityRouteImport } from './routes/Pages/security'
import { Route as PagesPrivacyRouteImport } from './routes/Pages/privacy'
import { Route as PagesPricingRouteImport } from './routes/Pages/pricing'
import { Route as PagesPressRouteImport } from './routes/Pages/press'
import { Route as PagesLicensesRouteImport } from './routes/Pages/licenses'
import { Route as PagesHelpRouteImport } from './routes/Pages/help'
import { Route as PagesDocumentationRouteImport } from './routes/Pages/documentation'
import { Route as PagesCookiePolicyRouteImport } from './routes/Pages/cookie-policy'
import { Route as PagesCommunityRouteImport } from './routes/Pages/community'
import { Route as PagesChangelogRouteImport } from './routes/Pages/changelog'
import { Route as PagesCareersRouteImport } from './routes/Pages/careers'
import { Route as PagesBlogRouteImport } from './routes/Pages/blog'
import { Route as PagesAboutRouteImport } from './routes/Pages/about'
import { Route as TeacherSubjectsIndexRouteImport } from './routes/teacher/subjects/index'
import { Route as TeacherClassesIndexRouteImport } from './routes/teacher/classes/index'
import { Route as StudentSubjectsIndexRouteImport } from './routes/student/subjects.index'
import { Route as StudentNotificationIndexRouteImport } from './routes/student/notification/index'
import { Route as AdminTeachersIndexRouteImport } from './routes/admin/teachers/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminGradesIndexRouteImport } from './routes/admin/grades/index'
import { Route as TeacherSubjectsSubjectCodeRouteImport } from './routes/teacher/subjects/$subjectCode'
import { Route as TeacherMarksClassIdRouteImport } from './routes/teacher/marks/$classId'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher/classes/$classId'
import { Route as TeacherAttendanceClassIdRouteImport } from './routes/teacher/attendance/$classId'
import { Route as StudentSubjectsSubjectCodeRouteImport } from './routes/student/subjects.$subjectCode'
import { Route as StudentNotificationNotificationIdRouteImport } from './routes/student/notification/$notificationId'
import { Route as AdminTeachersAddRouteImport } from './routes/admin/teachers/add'
import { Route as AdminStudentsAddRouteImport } from './routes/admin/students/add'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students/$studentId'
import { Route as AdminGradesNameRouteImport } from './routes/admin/grades/$name'
import { Route as AdminTeachersTeacherIdIndexRouteImport } from './routes/admin/teachers/$teacherId/index'
import { Route as AdminTeachersTeacherIdAssignementsRouteImport } from './routes/admin/teachers/$teacherId/assignements'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const PagesTermsRoute = PagesTermsRouteImport.update({
  id: '/Pages/terms',
  path: '/Pages/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSecurityRoute = PagesSecurityRouteImport.update({
  id: '/Pages/security',
  path: '/Pages/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPrivacyRoute = PagesPrivacyRouteImport.update({
  id: '/Pages/privacy',
  path: '/Pages/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPricingRoute = PagesPricingRouteImport.update({
  id: '/Pages/pricing',
  path: '/Pages/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPressRoute = PagesPressRouteImport.update({
  id: '/Pages/press',
  path: '/Pages/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicensesRoute = PagesLicensesRouteImport.update({
  id: '/Pages/licenses',
  path: '/Pages/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHelpRoute = PagesHelpRouteImport.update({
  id: '/Pages/help',
  path: '/Pages/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDocumentationRoute = PagesDocumentationRouteImport.update({
  id: '/Pages/documentation',
  path: '/Pages/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookiePolicyRoute = PagesCookiePolicyRouteImport.update({
  id: '/Pages/cookie-policy',
  path: '/Pages/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCommunityRoute = PagesCommunityRouteImport.update({
  id: '/Pages/community',
  path: '/Pages/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesChangelogRoute = PagesChangelogRouteImport.update({
  id: '/Pages/changelog',
  path: '/Pages/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCareersRoute = PagesCareersRouteImport.update({
  id: '/Pages/careers',
  path: '/Pages/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBlogRoute = PagesBlogRouteImport.update({
  id: '/Pages/blog',
  path: '/Pages/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/Pages/about',
  path: '/Pages/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubjectsIndexRoute = TeacherSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesIndexRoute = TeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentSubjectsIndexRoute = StudentSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationIndexRoute =
  StudentNotificationIndexRouteImport.update({
    id: '/notification/',
    path: '/notification/',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminTeachersIndexRoute = AdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGradesIndexRoute = AdminGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSubjectsSubjectCodeRoute =
  TeacherSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherMarksClassIdRoute = TeacherMarksClassIdRouteImport.update({
  id: '/marks/$classId',
  path: '/marks/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceClassIdRoute =
  TeacherAttendanceClassIdRouteImport.update({
    id: '/attendance/$classId',
    path: '/attendance/$classId',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentSubjectsSubjectCodeRoute =
  StudentSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentNotificationNotificationIdRoute =
  StudentNotificationNotificationIdRouteImport.update({
    id: '/notification/$notificationId',
    path: '/notification/$notificationId',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminTeachersAddRoute = AdminTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsAddRoute = AdminStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGradesNameRoute = AdminGradesNameRouteImport.update({
  id: '/grades/$name',
  path: '/grades/$name',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersTeacherIdIndexRoute =
  AdminTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTeachersTeacherIdAssignementsRoute =
  AdminTeachersTeacherIdAssignementsRouteImport.update({
    id: '/teachers/$teacherId/assignements',
    path: '/teachers/$teacherId/assignements',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/grades/$name': typeof AdminGradesNameRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/admin/grades/': typeof AdminGradesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/student/notification/': typeof StudentNotificationIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/admin/teachers/$teacherId/assignements': typeof AdminTeachersTeacherIdAssignementsRoute
  '/admin/teachers/$teacherId/': typeof AdminTeachersTeacherIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/grades/$name': typeof AdminGradesNameRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/admin/grades': typeof AdminGradesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/student/notification': typeof StudentNotificationIndexRoute
  '/student/subjects': typeof StudentSubjectsIndexRoute
  '/teacher/classes': typeof TeacherClassesIndexRoute
  '/teacher/subjects': typeof TeacherSubjectsIndexRoute
  '/admin/teachers/$teacherId/assignements': typeof AdminTeachersTeacherIdAssignementsRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/admin/grades/$name': typeof AdminGradesNameRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/students/add': typeof AdminStudentsAddRoute
  '/admin/teachers/add': typeof AdminTeachersAddRoute
  '/student/notification/$notificationId': typeof StudentNotificationNotificationIdRoute
  '/student/subjects/$subjectCode': typeof StudentSubjectsSubjectCodeRoute
  '/teacher/attendance/$classId': typeof TeacherAttendanceClassIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/marks/$classId': typeof TeacherMarksClassIdRoute
  '/teacher/subjects/$subjectCode': typeof TeacherSubjectsSubjectCodeRoute
  '/admin/grades/': typeof AdminGradesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/student/notification/': typeof StudentNotificationIndexRoute
  '/student/subjects/': typeof StudentSubjectsIndexRoute
  '/teacher/classes/': typeof TeacherClassesIndexRoute
  '/teacher/subjects/': typeof TeacherSubjectsIndexRoute
  '/admin/teachers/$teacherId/assignements': typeof AdminTeachersTeacherIdAssignementsRoute
  '/admin/teachers/$teacherId/': typeof AdminTeachersTeacherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/grades/$name'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/marks/$classId'
    | '/teacher/subjects/$subjectCode'
    | '/admin/grades/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/student/notification/'
    | '/student/subjects/'
    | '/teacher/classes/'
    | '/teacher/subjects/'
    | '/admin/teachers/$teacherId/assignements'
    | '/admin/teachers/$teacherId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/grades/$name'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/marks/$classId'
    | '/teacher/subjects/$subjectCode'
    | '/admin/grades'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/notification'
    | '/student/subjects'
    | '/teacher/classes'
    | '/teacher/subjects'
    | '/admin/teachers/$teacherId/assignements'
    | '/admin/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/log-in'
    | '/sign-up'
    | '/student'
    | '/teacher'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/settings'
    | '/admin/grades/$name'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/add'
    | '/student/notification/$notificationId'
    | '/student/subjects/$subjectCode'
    | '/teacher/attendance/$classId'
    | '/teacher/classes/$classId'
    | '/teacher/marks/$classId'
    | '/teacher/subjects/$subjectCode'
    | '/admin/grades/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/student/notification/'
    | '/student/subjects/'
    | '/teacher/classes/'
    | '/teacher/subjects/'
    | '/admin/teachers/$teacherId/assignements'
    | '/admin/teachers/$teacherId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LogInRoute: typeof LogInRoute
  SignUpRoute: typeof SignUpRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBlogRoute: typeof PagesBlogRoute
  PagesCareersRoute: typeof PagesCareersRoute
  PagesChangelogRoute: typeof PagesChangelogRoute
  PagesCommunityRoute: typeof PagesCommunityRoute
  PagesCookiePolicyRoute: typeof PagesCookiePolicyRoute
  PagesDocumentationRoute: typeof PagesDocumentationRoute
  PagesHelpRoute: typeof PagesHelpRoute
  PagesLicensesRoute: typeof PagesLicensesRoute
  PagesPressRoute: typeof PagesPressRoute
  PagesPricingRoute: typeof PagesPricingRoute
  PagesPrivacyRoute: typeof PagesPrivacyRoute
  PagesSecurityRoute: typeof PagesSecurityRoute
  PagesTermsRoute: typeof PagesTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/Pages/terms': {
      id: '/Pages/terms'
      path: '/Pages/terms'
      fullPath: '/Pages/terms'
      preLoaderRoute: typeof PagesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/security': {
      id: '/Pages/security'
      path: '/Pages/security'
      fullPath: '/Pages/security'
      preLoaderRoute: typeof PagesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/privacy': {
      id: '/Pages/privacy'
      path: '/Pages/privacy'
      fullPath: '/Pages/privacy'
      preLoaderRoute: typeof PagesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/pricing': {
      id: '/Pages/pricing'
      path: '/Pages/pricing'
      fullPath: '/Pages/pricing'
      preLoaderRoute: typeof PagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/press': {
      id: '/Pages/press'
      path: '/Pages/press'
      fullPath: '/Pages/press'
      preLoaderRoute: typeof PagesPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/licenses': {
      id: '/Pages/licenses'
      path: '/Pages/licenses'
      fullPath: '/Pages/licenses'
      preLoaderRoute: typeof PagesLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/help': {
      id: '/Pages/help'
      path: '/Pages/help'
      fullPath: '/Pages/help'
      preLoaderRoute: typeof PagesHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/documentation': {
      id: '/Pages/documentation'
      path: '/Pages/documentation'
      fullPath: '/Pages/documentation'
      preLoaderRoute: typeof PagesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/cookie-policy': {
      id: '/Pages/cookie-policy'
      path: '/Pages/cookie-policy'
      fullPath: '/Pages/cookie-policy'
      preLoaderRoute: typeof PagesCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/community': {
      id: '/Pages/community'
      path: '/Pages/community'
      fullPath: '/Pages/community'
      preLoaderRoute: typeof PagesCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/changelog': {
      id: '/Pages/changelog'
      path: '/Pages/changelog'
      fullPath: '/Pages/changelog'
      preLoaderRoute: typeof PagesChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/careers': {
      id: '/Pages/careers'
      path: '/Pages/careers'
      fullPath: '/Pages/careers'
      preLoaderRoute: typeof PagesCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/blog': {
      id: '/Pages/blog'
      path: '/Pages/blog'
      fullPath: '/Pages/blog'
      preLoaderRoute: typeof PagesBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/about': {
      id: '/Pages/about'
      path: '/Pages/about'
      fullPath: '/Pages/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/subjects/': {
      id: '/teacher/subjects/'
      path: '/subjects'
      fullPath: '/teacher/subjects/'
      preLoaderRoute: typeof TeacherSubjectsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/': {
      id: '/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof TeacherClassesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/subjects/': {
      id: '/student/subjects/'
      path: '/subjects'
      fullPath: '/student/subjects/'
      preLoaderRoute: typeof StudentSubjectsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification/': {
      id: '/student/notification/'
      path: '/notification'
      fullPath: '/student/notification/'
      preLoaderRoute: typeof StudentNotificationIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/teachers/': {
      id: '/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AdminTeachersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grades/': {
      id: '/admin/grades/'
      path: '/grades'
      fullPath: '/admin/grades/'
      preLoaderRoute: typeof AdminGradesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/subjects/$subjectCode': {
      id: '/teacher/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/teacher/subjects/$subjectCode'
      preLoaderRoute: typeof TeacherSubjectsSubjectCodeRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/marks/$classId': {
      id: '/teacher/marks/$classId'
      path: '/marks/$classId'
      fullPath: '/teacher/marks/$classId'
      preLoaderRoute: typeof TeacherMarksClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance/$classId': {
      id: '/teacher/attendance/$classId'
      path: '/attendance/$classId'
      fullPath: '/teacher/attendance/$classId'
      preLoaderRoute: typeof TeacherAttendanceClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/subjects/$subjectCode': {
      id: '/student/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/student/subjects/$subjectCode'
      preLoaderRoute: typeof StudentSubjectsSubjectCodeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification/$notificationId': {
      id: '/student/notification/$notificationId'
      path: '/notification/$notificationId'
      fullPath: '/student/notification/$notificationId'
      preLoaderRoute: typeof StudentNotificationNotificationIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/teachers/add': {
      id: '/admin/teachers/add'
      path: '/teachers/add'
      fullPath: '/admin/teachers/add'
      preLoaderRoute: typeof AdminTeachersAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/add': {
      id: '/admin/students/add'
      path: '/students/add'
      fullPath: '/admin/students/add'
      preLoaderRoute: typeof AdminStudentsAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grades/$name': {
      id: '/admin/grades/$name'
      path: '/grades/$name'
      fullPath: '/admin/grades/$name'
      preLoaderRoute: typeof AdminGradesNameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/$teacherId/': {
      id: '/admin/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId/'
      preLoaderRoute: typeof AdminTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/$teacherId/assignements': {
      id: '/admin/teachers/$teacherId/assignements'
      path: '/teachers/$teacherId/assignements'
      fullPath: '/admin/teachers/$teacherId/assignements'
      preLoaderRoute: typeof AdminTeachersTeacherIdAssignementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminGradesNameRoute: typeof AdminGradesNameRoute
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
  AdminStudentsAddRoute: typeof AdminStudentsAddRoute
  AdminTeachersAddRoute: typeof AdminTeachersAddRoute
  AdminGradesIndexRoute: typeof AdminGradesIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminTeachersIndexRoute: typeof AdminTeachersIndexRoute
  AdminTeachersTeacherIdAssignementsRoute: typeof AdminTeachersTeacherIdAssignementsRoute
  AdminTeachersTeacherIdIndexRoute: typeof AdminTeachersTeacherIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminGradesNameRoute: AdminGradesNameRoute,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
  AdminStudentsAddRoute: AdminStudentsAddRoute,
  AdminTeachersAddRoute: AdminTeachersAddRoute,
  AdminGradesIndexRoute: AdminGradesIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminTeachersIndexRoute: AdminTeachersIndexRoute,
  AdminTeachersTeacherIdAssignementsRoute:
    AdminTeachersTeacherIdAssignementsRoute,
  AdminTeachersTeacherIdIndexRoute: AdminTeachersTeacherIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentNotificationNotificationIdRoute: typeof StudentNotificationNotificationIdRoute
  StudentSubjectsSubjectCodeRoute: typeof StudentSubjectsSubjectCodeRoute
  StudentNotificationIndexRoute: typeof StudentNotificationIndexRoute
  StudentSubjectsIndexRoute: typeof StudentSubjectsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentNotificationNotificationIdRoute:
    StudentNotificationNotificationIdRoute,
  StudentSubjectsSubjectCodeRoute: StudentSubjectsSubjectCodeRoute,
  StudentNotificationIndexRoute: StudentNotificationIndexRoute,
  StudentSubjectsIndexRoute: StudentSubjectsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherAttendanceClassIdRoute: typeof TeacherAttendanceClassIdRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherMarksClassIdRoute: typeof TeacherMarksClassIdRoute
  TeacherSubjectsSubjectCodeRoute: typeof TeacherSubjectsSubjectCodeRoute
  TeacherClassesIndexRoute: typeof TeacherClassesIndexRoute
  TeacherSubjectsIndexRoute: typeof TeacherSubjectsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherAttendanceClassIdRoute: TeacherAttendanceClassIdRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherMarksClassIdRoute: TeacherMarksClassIdRoute,
  TeacherSubjectsSubjectCodeRoute: TeacherSubjectsSubjectCodeRoute,
  TeacherClassesIndexRoute: TeacherClassesIndexRoute,
  TeacherSubjectsIndexRoute: TeacherSubjectsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LogInRoute: LogInRoute,
  SignUpRoute: SignUpRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  PagesAboutRoute: PagesAboutRoute,
  PagesBlogRoute: PagesBlogRoute,
  PagesCareersRoute: PagesCareersRoute,
  PagesChangelogRoute: PagesChangelogRoute,
  PagesCommunityRoute: PagesCommunityRoute,
  PagesCookiePolicyRoute: PagesCookiePolicyRoute,
  PagesDocumentationRoute: PagesDocumentationRoute,
  PagesHelpRoute: PagesHelpRoute,
  PagesLicensesRoute: PagesLicensesRoute,
  PagesPressRoute: PagesPressRoute,
  PagesPricingRoute: PagesPricingRoute,
  PagesPrivacyRoute: PagesPrivacyRoute,
  PagesSecurityRoute: PagesSecurityRoute,
  PagesTermsRoute: PagesTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
