/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTeacherRouteImport } from './routes/_auth/teacher'
import { Route as AuthStudentRouteImport } from './routes/_auth/student'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as PagesTermsRouteImport } from './routes/Pages/terms'
import { Route as PagesSecurityRouteImport } from './routes/Pages/security'
import { Route as PagesPrivacyRouteImport } from './routes/Pages/privacy'
import { Route as PagesPricingRouteImport } from './routes/Pages/pricing'
import { Route as PagesPressRouteImport } from './routes/Pages/press'
import { Route as PagesLicensesRouteImport } from './routes/Pages/licenses'
import { Route as PagesHelpRouteImport } from './routes/Pages/help'
import { Route as PagesDocumentationRouteImport } from './routes/Pages/documentation'
import { Route as PagesCookiePolicyRouteImport } from './routes/Pages/cookie-policy'
import { Route as PagesCommunityRouteImport } from './routes/Pages/community'
import { Route as PagesChangelogRouteImport } from './routes/Pages/changelog'
import { Route as PagesCareersRouteImport } from './routes/Pages/careers'
import { Route as PagesBlogRouteImport } from './routes/Pages/blog'
import { Route as PagesAboutRouteImport } from './routes/Pages/about'
import { Route as AuthTeacherSettingsRouteImport } from './routes/_auth/teacher/settings'
import { Route as AuthTeacherCreateAnnouncementRouteImport } from './routes/_auth/teacher/createAnnouncement'
import { Route as AuthTeacherCalendarRouteImport } from './routes/_auth/teacher/calendar'
import { Route as AuthStudentSettingsRouteImport } from './routes/_auth/student/settings'
import { Route as AuthStudentCalendarRouteImport } from './routes/_auth/student/calendar'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth/admin/settings'
import { Route as AuthAdminDashboardRouteImport } from './routes/_auth/admin/dashboard'
import { Route as AuthAdminCreateAnnouncementRouteImport } from './routes/_auth/admin/createAnnouncement'
import { Route as AuthAdminCalendarRouteImport } from './routes/_auth/admin/calendar'
import { Route as AuthTeacherSubjectsIndexRouteImport } from './routes/_auth/teacher/subjects/index'
import { Route as AuthTeacherClassesIndexRouteImport } from './routes/_auth/teacher/classes/index'
import { Route as AuthTeacherAnnouncementsIndexRouteImport } from './routes/_auth/teacher/announcements/index'
import { Route as AuthStudentSubjectsIndexRouteImport } from './routes/_auth/student/subjects.index'
import { Route as AuthStudentAnnouncementsIndexRouteImport } from './routes/_auth/student/announcements/index'
import { Route as AuthAdminTeachersIndexRouteImport } from './routes/_auth/admin/teachers/index'
import { Route as AuthAdminStudentsIndexRouteImport } from './routes/_auth/admin/students/index'
import { Route as AuthAdminGradesIndexRouteImport } from './routes/_auth/admin/grades/index'
import { Route as AuthAdminAnnouncementsIndexRouteImport } from './routes/_auth/admin/announcements/index'
import { Route as AuthTeacherSubjectsSubjectCodeRouteImport } from './routes/_auth/teacher/subjects/$subjectCode'
import { Route as AuthTeacherMarksClassIdRouteImport } from './routes/_auth/teacher/marks/$classId'
import { Route as AuthTeacherClassesClassIdRouteImport } from './routes/_auth/teacher/classes/$classId'
import { Route as AuthTeacherAnnouncementsAnnouncementTitleSlugRouteImport } from './routes/_auth/teacher/announcements/$announcementTitleSlug'
import { Route as AuthStudentSubjectsSubjectCodeRouteImport } from './routes/_auth/student/subjects.$subjectCode'
import { Route as AuthStudentAnnouncementsAnnouncementTitleSlugRouteImport } from './routes/_auth/student/announcements/$announcementTitleSlug'
import { Route as AuthApiAuthSplatRouteImport } from './routes/_auth/api/auth.$'
import { Route as AuthAdminTeachersAddRouteImport } from './routes/_auth/admin/teachers/add'
import { Route as AuthAdminStudentsAddRouteImport } from './routes/_auth/admin/students/add'
import { Route as AuthAdminStudentsStudentIdRouteImport } from './routes/_auth/admin/students/$studentId'
import { Route as AuthAdminGradesNameRouteImport } from './routes/_auth/admin/grades/$name'
import { Route as AuthAdminAnnouncementsAnnouncementTitleSlugRouteImport } from './routes/_auth/admin/announcements/$announcementTitleSlug'
import { Route as AuthAdminTeachersTeacherIdIndexRouteImport } from './routes/_auth/admin/teachers/$teacherId/index'
import { Route as AuthAdminTeachersTeacherIdAssignementsRouteImport } from './routes/_auth/admin/teachers/$teacherId/assignements'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeacherRoute = AuthTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const PagesTermsRoute = PagesTermsRouteImport.update({
  id: '/Pages/terms',
  path: '/Pages/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSecurityRoute = PagesSecurityRouteImport.update({
  id: '/Pages/security',
  path: '/Pages/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPrivacyRoute = PagesPrivacyRouteImport.update({
  id: '/Pages/privacy',
  path: '/Pages/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPricingRoute = PagesPricingRouteImport.update({
  id: '/Pages/pricing',
  path: '/Pages/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPressRoute = PagesPressRouteImport.update({
  id: '/Pages/press',
  path: '/Pages/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicensesRoute = PagesLicensesRouteImport.update({
  id: '/Pages/licenses',
  path: '/Pages/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesHelpRoute = PagesHelpRouteImport.update({
  id: '/Pages/help',
  path: '/Pages/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesDocumentationRoute = PagesDocumentationRouteImport.update({
  id: '/Pages/documentation',
  path: '/Pages/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookiePolicyRoute = PagesCookiePolicyRouteImport.update({
  id: '/Pages/cookie-policy',
  path: '/Pages/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCommunityRoute = PagesCommunityRouteImport.update({
  id: '/Pages/community',
  path: '/Pages/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesChangelogRoute = PagesChangelogRouteImport.update({
  id: '/Pages/changelog',
  path: '/Pages/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCareersRoute = PagesCareersRouteImport.update({
  id: '/Pages/careers',
  path: '/Pages/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBlogRoute = PagesBlogRouteImport.update({
  id: '/Pages/blog',
  path: '/Pages/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/Pages/about',
  path: '/Pages/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeacherSettingsRoute = AuthTeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthTeacherRoute,
} as any)
const AuthTeacherCreateAnnouncementRoute =
  AuthTeacherCreateAnnouncementRouteImport.update({
    id: '/createAnnouncement',
    path: '/createAnnouncement',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthTeacherCalendarRoute = AuthTeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthTeacherRoute,
} as any)
const AuthStudentSettingsRoute = AuthStudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentCalendarRoute = AuthStudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDashboardRoute = AuthAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCreateAnnouncementRoute =
  AuthAdminCreateAnnouncementRouteImport.update({
    id: '/createAnnouncement',
    path: '/createAnnouncement',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthAdminCalendarRoute = AuthAdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthTeacherSubjectsIndexRoute =
  AuthTeacherSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthTeacherClassesIndexRoute = AuthTeacherClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AuthTeacherRoute,
} as any)
const AuthTeacherAnnouncementsIndexRoute =
  AuthTeacherAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthStudentSubjectsIndexRoute =
  AuthStudentSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthStudentAnnouncementsIndexRoute =
  AuthStudentAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthAdminTeachersIndexRoute = AuthAdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminStudentsIndexRoute = AuthAdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminGradesIndexRoute = AuthAdminGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAnnouncementsIndexRoute =
  AuthAdminAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthTeacherSubjectsSubjectCodeRoute =
  AuthTeacherSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthTeacherMarksClassIdRoute = AuthTeacherMarksClassIdRouteImport.update({
  id: '/marks/$classId',
  path: '/marks/$classId',
  getParentRoute: () => AuthTeacherRoute,
} as any)
const AuthTeacherClassesClassIdRoute =
  AuthTeacherClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthTeacherAnnouncementsAnnouncementTitleSlugRoute =
  AuthTeacherAnnouncementsAnnouncementTitleSlugRouteImport.update({
    id: '/announcements/$announcementTitleSlug',
    path: '/announcements/$announcementTitleSlug',
    getParentRoute: () => AuthTeacherRoute,
  } as any)
const AuthStudentSubjectsSubjectCodeRoute =
  AuthStudentSubjectsSubjectCodeRouteImport.update({
    id: '/subjects/$subjectCode',
    path: '/subjects/$subjectCode',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthStudentAnnouncementsAnnouncementTitleSlugRoute =
  AuthStudentAnnouncementsAnnouncementTitleSlugRouteImport.update({
    id: '/announcements/$announcementTitleSlug',
    path: '/announcements/$announcementTitleSlug',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthApiAuthSplatRoute = AuthApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminTeachersAddRoute = AuthAdminTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminStudentsAddRoute = AuthAdminStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminStudentsStudentIdRoute =
  AuthAdminStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthAdminGradesNameRoute = AuthAdminGradesNameRouteImport.update({
  id: '/grades/$name',
  path: '/grades/$name',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAnnouncementsAnnouncementTitleSlugRoute =
  AuthAdminAnnouncementsAnnouncementTitleSlugRouteImport.update({
    id: '/announcements/$announcementTitleSlug',
    path: '/announcements/$announcementTitleSlug',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthAdminTeachersTeacherIdIndexRoute =
  AuthAdminTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AuthAdminRoute,
  } as any)
const AuthAdminTeachersTeacherIdAssignementsRoute =
  AuthAdminTeachersTeacherIdAssignementsRouteImport.update({
    id: '/teachers/$teacherId/assignements',
    path: '/teachers/$teacherId/assignements',
    getParentRoute: () => AuthAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/teacher': typeof AuthTeacherRouteWithChildren
  '/admin/calendar': typeof AuthAdminCalendarRoute
  '/admin/createAnnouncement': typeof AuthAdminCreateAnnouncementRoute
  '/admin/dashboard': typeof AuthAdminDashboardRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/student/calendar': typeof AuthStudentCalendarRoute
  '/student/settings': typeof AuthStudentSettingsRoute
  '/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/teacher/createAnnouncement': typeof AuthTeacherCreateAnnouncementRoute
  '/teacher/settings': typeof AuthTeacherSettingsRoute
  '/admin/announcements/$announcementTitleSlug': typeof AuthAdminAnnouncementsAnnouncementTitleSlugRoute
  '/admin/grades/$name': typeof AuthAdminGradesNameRoute
  '/admin/students/$studentId': typeof AuthAdminStudentsStudentIdRoute
  '/admin/students/add': typeof AuthAdminStudentsAddRoute
  '/admin/teachers/add': typeof AuthAdminTeachersAddRoute
  '/api/auth/$': typeof AuthApiAuthSplatRoute
  '/student/announcements/$announcementTitleSlug': typeof AuthStudentAnnouncementsAnnouncementTitleSlugRoute
  '/student/subjects/$subjectCode': typeof AuthStudentSubjectsSubjectCodeRoute
  '/teacher/announcements/$announcementTitleSlug': typeof AuthTeacherAnnouncementsAnnouncementTitleSlugRoute
  '/teacher/classes/$classId': typeof AuthTeacherClassesClassIdRoute
  '/teacher/marks/$classId': typeof AuthTeacherMarksClassIdRoute
  '/teacher/subjects/$subjectCode': typeof AuthTeacherSubjectsSubjectCodeRoute
  '/admin/announcements/': typeof AuthAdminAnnouncementsIndexRoute
  '/admin/grades/': typeof AuthAdminGradesIndexRoute
  '/admin/students/': typeof AuthAdminStudentsIndexRoute
  '/admin/teachers/': typeof AuthAdminTeachersIndexRoute
  '/student/announcements/': typeof AuthStudentAnnouncementsIndexRoute
  '/student/subjects/': typeof AuthStudentSubjectsIndexRoute
  '/teacher/announcements/': typeof AuthTeacherAnnouncementsIndexRoute
  '/teacher/classes/': typeof AuthTeacherClassesIndexRoute
  '/teacher/subjects/': typeof AuthTeacherSubjectsIndexRoute
  '/admin/teachers/$teacherId/assignements': typeof AuthAdminTeachersTeacherIdAssignementsRoute
  '/admin/teachers/$teacherId/': typeof AuthAdminTeachersTeacherIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/teacher': typeof AuthTeacherRouteWithChildren
  '/admin/calendar': typeof AuthAdminCalendarRoute
  '/admin/createAnnouncement': typeof AuthAdminCreateAnnouncementRoute
  '/admin/dashboard': typeof AuthAdminDashboardRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/student/calendar': typeof AuthStudentCalendarRoute
  '/student/settings': typeof AuthStudentSettingsRoute
  '/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/teacher/createAnnouncement': typeof AuthTeacherCreateAnnouncementRoute
  '/teacher/settings': typeof AuthTeacherSettingsRoute
  '/admin/announcements/$announcementTitleSlug': typeof AuthAdminAnnouncementsAnnouncementTitleSlugRoute
  '/admin/grades/$name': typeof AuthAdminGradesNameRoute
  '/admin/students/$studentId': typeof AuthAdminStudentsStudentIdRoute
  '/admin/students/add': typeof AuthAdminStudentsAddRoute
  '/admin/teachers/add': typeof AuthAdminTeachersAddRoute
  '/api/auth/$': typeof AuthApiAuthSplatRoute
  '/student/announcements/$announcementTitleSlug': typeof AuthStudentAnnouncementsAnnouncementTitleSlugRoute
  '/student/subjects/$subjectCode': typeof AuthStudentSubjectsSubjectCodeRoute
  '/teacher/announcements/$announcementTitleSlug': typeof AuthTeacherAnnouncementsAnnouncementTitleSlugRoute
  '/teacher/classes/$classId': typeof AuthTeacherClassesClassIdRoute
  '/teacher/marks/$classId': typeof AuthTeacherMarksClassIdRoute
  '/teacher/subjects/$subjectCode': typeof AuthTeacherSubjectsSubjectCodeRoute
  '/admin/announcements': typeof AuthAdminAnnouncementsIndexRoute
  '/admin/grades': typeof AuthAdminGradesIndexRoute
  '/admin/students': typeof AuthAdminStudentsIndexRoute
  '/admin/teachers': typeof AuthAdminTeachersIndexRoute
  '/student/announcements': typeof AuthStudentAnnouncementsIndexRoute
  '/student/subjects': typeof AuthStudentSubjectsIndexRoute
  '/teacher/announcements': typeof AuthTeacherAnnouncementsIndexRoute
  '/teacher/classes': typeof AuthTeacherClassesIndexRoute
  '/teacher/subjects': typeof AuthTeacherSubjectsIndexRoute
  '/admin/teachers/$teacherId/assignements': typeof AuthAdminTeachersTeacherIdAssignementsRoute
  '/admin/teachers/$teacherId': typeof AuthAdminTeachersTeacherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/Pages/about': typeof PagesAboutRoute
  '/Pages/blog': typeof PagesBlogRoute
  '/Pages/careers': typeof PagesCareersRoute
  '/Pages/changelog': typeof PagesChangelogRoute
  '/Pages/community': typeof PagesCommunityRoute
  '/Pages/cookie-policy': typeof PagesCookiePolicyRoute
  '/Pages/documentation': typeof PagesDocumentationRoute
  '/Pages/help': typeof PagesHelpRoute
  '/Pages/licenses': typeof PagesLicensesRoute
  '/Pages/press': typeof PagesPressRoute
  '/Pages/pricing': typeof PagesPricingRoute
  '/Pages/privacy': typeof PagesPrivacyRoute
  '/Pages/security': typeof PagesSecurityRoute
  '/Pages/terms': typeof PagesTermsRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/student': typeof AuthStudentRouteWithChildren
  '/_auth/teacher': typeof AuthTeacherRouteWithChildren
  '/_auth/admin/calendar': typeof AuthAdminCalendarRoute
  '/_auth/admin/createAnnouncement': typeof AuthAdminCreateAnnouncementRoute
  '/_auth/admin/dashboard': typeof AuthAdminDashboardRoute
  '/_auth/admin/settings': typeof AuthAdminSettingsRoute
  '/_auth/student/calendar': typeof AuthStudentCalendarRoute
  '/_auth/student/settings': typeof AuthStudentSettingsRoute
  '/_auth/teacher/calendar': typeof AuthTeacherCalendarRoute
  '/_auth/teacher/createAnnouncement': typeof AuthTeacherCreateAnnouncementRoute
  '/_auth/teacher/settings': typeof AuthTeacherSettingsRoute
  '/_auth/admin/announcements/$announcementTitleSlug': typeof AuthAdminAnnouncementsAnnouncementTitleSlugRoute
  '/_auth/admin/grades/$name': typeof AuthAdminGradesNameRoute
  '/_auth/admin/students/$studentId': typeof AuthAdminStudentsStudentIdRoute
  '/_auth/admin/students/add': typeof AuthAdminStudentsAddRoute
  '/_auth/admin/teachers/add': typeof AuthAdminTeachersAddRoute
  '/_auth/api/auth/$': typeof AuthApiAuthSplatRoute
  '/_auth/student/announcements/$announcementTitleSlug': typeof AuthStudentAnnouncementsAnnouncementTitleSlugRoute
  '/_auth/student/subjects/$subjectCode': typeof AuthStudentSubjectsSubjectCodeRoute
  '/_auth/teacher/announcements/$announcementTitleSlug': typeof AuthTeacherAnnouncementsAnnouncementTitleSlugRoute
  '/_auth/teacher/classes/$classId': typeof AuthTeacherClassesClassIdRoute
  '/_auth/teacher/marks/$classId': typeof AuthTeacherMarksClassIdRoute
  '/_auth/teacher/subjects/$subjectCode': typeof AuthTeacherSubjectsSubjectCodeRoute
  '/_auth/admin/announcements/': typeof AuthAdminAnnouncementsIndexRoute
  '/_auth/admin/grades/': typeof AuthAdminGradesIndexRoute
  '/_auth/admin/students/': typeof AuthAdminStudentsIndexRoute
  '/_auth/admin/teachers/': typeof AuthAdminTeachersIndexRoute
  '/_auth/student/announcements/': typeof AuthStudentAnnouncementsIndexRoute
  '/_auth/student/subjects/': typeof AuthStudentSubjectsIndexRoute
  '/_auth/teacher/announcements/': typeof AuthTeacherAnnouncementsIndexRoute
  '/_auth/teacher/classes/': typeof AuthTeacherClassesIndexRoute
  '/_auth/teacher/subjects/': typeof AuthTeacherSubjectsIndexRoute
  '/_auth/admin/teachers/$teacherId/assignements': typeof AuthAdminTeachersTeacherIdAssignementsRoute
  '/_auth/admin/teachers/$teacherId/': typeof AuthAdminTeachersTeacherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log-in'
    | '/sign-up'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/createAnnouncement'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/createAnnouncement'
    | '/teacher/settings'
    | '/admin/announcements/$announcementTitleSlug'
    | '/admin/grades/$name'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/add'
    | '/api/auth/$'
    | '/student/announcements/$announcementTitleSlug'
    | '/student/subjects/$subjectCode'
    | '/teacher/announcements/$announcementTitleSlug'
    | '/teacher/classes/$classId'
    | '/teacher/marks/$classId'
    | '/teacher/subjects/$subjectCode'
    | '/admin/announcements/'
    | '/admin/grades/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/student/announcements/'
    | '/student/subjects/'
    | '/teacher/announcements/'
    | '/teacher/classes/'
    | '/teacher/subjects/'
    | '/admin/teachers/$teacherId/assignements'
    | '/admin/teachers/$teacherId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log-in'
    | '/sign-up'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/createAnnouncement'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/student/calendar'
    | '/student/settings'
    | '/teacher/calendar'
    | '/teacher/createAnnouncement'
    | '/teacher/settings'
    | '/admin/announcements/$announcementTitleSlug'
    | '/admin/grades/$name'
    | '/admin/students/$studentId'
    | '/admin/students/add'
    | '/admin/teachers/add'
    | '/api/auth/$'
    | '/student/announcements/$announcementTitleSlug'
    | '/student/subjects/$subjectCode'
    | '/teacher/announcements/$announcementTitleSlug'
    | '/teacher/classes/$classId'
    | '/teacher/marks/$classId'
    | '/teacher/subjects/$subjectCode'
    | '/admin/announcements'
    | '/admin/grades'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/announcements'
    | '/student/subjects'
    | '/teacher/announcements'
    | '/teacher/classes'
    | '/teacher/subjects'
    | '/admin/teachers/$teacherId/assignements'
    | '/admin/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/log-in'
    | '/sign-up'
    | '/Pages/about'
    | '/Pages/blog'
    | '/Pages/careers'
    | '/Pages/changelog'
    | '/Pages/community'
    | '/Pages/cookie-policy'
    | '/Pages/documentation'
    | '/Pages/help'
    | '/Pages/licenses'
    | '/Pages/press'
    | '/Pages/pricing'
    | '/Pages/privacy'
    | '/Pages/security'
    | '/Pages/terms'
    | '/_auth/admin'
    | '/_auth/student'
    | '/_auth/teacher'
    | '/_auth/admin/calendar'
    | '/_auth/admin/createAnnouncement'
    | '/_auth/admin/dashboard'
    | '/_auth/admin/settings'
    | '/_auth/student/calendar'
    | '/_auth/student/settings'
    | '/_auth/teacher/calendar'
    | '/_auth/teacher/createAnnouncement'
    | '/_auth/teacher/settings'
    | '/_auth/admin/announcements/$announcementTitleSlug'
    | '/_auth/admin/grades/$name'
    | '/_auth/admin/students/$studentId'
    | '/_auth/admin/students/add'
    | '/_auth/admin/teachers/add'
    | '/_auth/api/auth/$'
    | '/_auth/student/announcements/$announcementTitleSlug'
    | '/_auth/student/subjects/$subjectCode'
    | '/_auth/teacher/announcements/$announcementTitleSlug'
    | '/_auth/teacher/classes/$classId'
    | '/_auth/teacher/marks/$classId'
    | '/_auth/teacher/subjects/$subjectCode'
    | '/_auth/admin/announcements/'
    | '/_auth/admin/grades/'
    | '/_auth/admin/students/'
    | '/_auth/admin/teachers/'
    | '/_auth/student/announcements/'
    | '/_auth/student/subjects/'
    | '/_auth/teacher/announcements/'
    | '/_auth/teacher/classes/'
    | '/_auth/teacher/subjects/'
    | '/_auth/admin/teachers/$teacherId/assignements'
    | '/_auth/admin/teachers/$teacherId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LogInRoute: typeof LogInRoute
  SignUpRoute: typeof SignUpRoute
  PagesAboutRoute: typeof PagesAboutRoute
  PagesBlogRoute: typeof PagesBlogRoute
  PagesCareersRoute: typeof PagesCareersRoute
  PagesChangelogRoute: typeof PagesChangelogRoute
  PagesCommunityRoute: typeof PagesCommunityRoute
  PagesCookiePolicyRoute: typeof PagesCookiePolicyRoute
  PagesDocumentationRoute: typeof PagesDocumentationRoute
  PagesHelpRoute: typeof PagesHelpRoute
  PagesLicensesRoute: typeof PagesLicensesRoute
  PagesPressRoute: typeof PagesPressRoute
  PagesPricingRoute: typeof PagesPricingRoute
  PagesPrivacyRoute: typeof PagesPrivacyRoute
  PagesSecurityRoute: typeof PagesSecurityRoute
  PagesTermsRoute: typeof PagesTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/teacher': {
      id: '/_auth/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthTeacherRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/student': {
      id: '/_auth/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/Pages/terms': {
      id: '/Pages/terms'
      path: '/Pages/terms'
      fullPath: '/Pages/terms'
      preLoaderRoute: typeof PagesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/security': {
      id: '/Pages/security'
      path: '/Pages/security'
      fullPath: '/Pages/security'
      preLoaderRoute: typeof PagesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/privacy': {
      id: '/Pages/privacy'
      path: '/Pages/privacy'
      fullPath: '/Pages/privacy'
      preLoaderRoute: typeof PagesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/pricing': {
      id: '/Pages/pricing'
      path: '/Pages/pricing'
      fullPath: '/Pages/pricing'
      preLoaderRoute: typeof PagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/press': {
      id: '/Pages/press'
      path: '/Pages/press'
      fullPath: '/Pages/press'
      preLoaderRoute: typeof PagesPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/licenses': {
      id: '/Pages/licenses'
      path: '/Pages/licenses'
      fullPath: '/Pages/licenses'
      preLoaderRoute: typeof PagesLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/help': {
      id: '/Pages/help'
      path: '/Pages/help'
      fullPath: '/Pages/help'
      preLoaderRoute: typeof PagesHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/documentation': {
      id: '/Pages/documentation'
      path: '/Pages/documentation'
      fullPath: '/Pages/documentation'
      preLoaderRoute: typeof PagesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/cookie-policy': {
      id: '/Pages/cookie-policy'
      path: '/Pages/cookie-policy'
      fullPath: '/Pages/cookie-policy'
      preLoaderRoute: typeof PagesCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/community': {
      id: '/Pages/community'
      path: '/Pages/community'
      fullPath: '/Pages/community'
      preLoaderRoute: typeof PagesCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/changelog': {
      id: '/Pages/changelog'
      path: '/Pages/changelog'
      fullPath: '/Pages/changelog'
      preLoaderRoute: typeof PagesChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/careers': {
      id: '/Pages/careers'
      path: '/Pages/careers'
      fullPath: '/Pages/careers'
      preLoaderRoute: typeof PagesCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/blog': {
      id: '/Pages/blog'
      path: '/Pages/blog'
      fullPath: '/Pages/blog'
      preLoaderRoute: typeof PagesBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Pages/about': {
      id: '/Pages/about'
      path: '/Pages/about'
      fullPath: '/Pages/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/teacher/settings': {
      id: '/_auth/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof AuthTeacherSettingsRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/createAnnouncement': {
      id: '/_auth/teacher/createAnnouncement'
      path: '/createAnnouncement'
      fullPath: '/teacher/createAnnouncement'
      preLoaderRoute: typeof AuthTeacherCreateAnnouncementRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/calendar': {
      id: '/_auth/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof AuthTeacherCalendarRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/student/settings': {
      id: '/_auth/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AuthStudentSettingsRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/calendar': {
      id: '/_auth/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof AuthStudentCalendarRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/admin/settings': {
      id: '/_auth/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/dashboard': {
      id: '/_auth/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthAdminDashboardRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/createAnnouncement': {
      id: '/_auth/admin/createAnnouncement'
      path: '/createAnnouncement'
      fullPath: '/admin/createAnnouncement'
      preLoaderRoute: typeof AuthAdminCreateAnnouncementRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/calendar': {
      id: '/_auth/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthAdminCalendarRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/teacher/subjects/': {
      id: '/_auth/teacher/subjects/'
      path: '/subjects'
      fullPath: '/teacher/subjects/'
      preLoaderRoute: typeof AuthTeacherSubjectsIndexRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/classes/': {
      id: '/_auth/teacher/classes/'
      path: '/classes'
      fullPath: '/teacher/classes/'
      preLoaderRoute: typeof AuthTeacherClassesIndexRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/announcements/': {
      id: '/_auth/teacher/announcements/'
      path: '/announcements'
      fullPath: '/teacher/announcements/'
      preLoaderRoute: typeof AuthTeacherAnnouncementsIndexRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/student/subjects/': {
      id: '/_auth/student/subjects/'
      path: '/subjects'
      fullPath: '/student/subjects/'
      preLoaderRoute: typeof AuthStudentSubjectsIndexRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/announcements/': {
      id: '/_auth/student/announcements/'
      path: '/announcements'
      fullPath: '/student/announcements/'
      preLoaderRoute: typeof AuthStudentAnnouncementsIndexRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/admin/teachers/': {
      id: '/_auth/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AuthAdminTeachersIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/students/': {
      id: '/_auth/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthAdminStudentsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/grades/': {
      id: '/_auth/admin/grades/'
      path: '/grades'
      fullPath: '/admin/grades/'
      preLoaderRoute: typeof AuthAdminGradesIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/announcements/': {
      id: '/_auth/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AuthAdminAnnouncementsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/teacher/subjects/$subjectCode': {
      id: '/_auth/teacher/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/teacher/subjects/$subjectCode'
      preLoaderRoute: typeof AuthTeacherSubjectsSubjectCodeRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/marks/$classId': {
      id: '/_auth/teacher/marks/$classId'
      path: '/marks/$classId'
      fullPath: '/teacher/marks/$classId'
      preLoaderRoute: typeof AuthTeacherMarksClassIdRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/classes/$classId': {
      id: '/_auth/teacher/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof AuthTeacherClassesClassIdRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/teacher/announcements/$announcementTitleSlug': {
      id: '/_auth/teacher/announcements/$announcementTitleSlug'
      path: '/announcements/$announcementTitleSlug'
      fullPath: '/teacher/announcements/$announcementTitleSlug'
      preLoaderRoute: typeof AuthTeacherAnnouncementsAnnouncementTitleSlugRouteImport
      parentRoute: typeof AuthTeacherRoute
    }
    '/_auth/student/subjects/$subjectCode': {
      id: '/_auth/student/subjects/$subjectCode'
      path: '/subjects/$subjectCode'
      fullPath: '/student/subjects/$subjectCode'
      preLoaderRoute: typeof AuthStudentSubjectsSubjectCodeRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/announcements/$announcementTitleSlug': {
      id: '/_auth/student/announcements/$announcementTitleSlug'
      path: '/announcements/$announcementTitleSlug'
      fullPath: '/student/announcements/$announcementTitleSlug'
      preLoaderRoute: typeof AuthStudentAnnouncementsAnnouncementTitleSlugRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/api/auth/$': {
      id: '/_auth/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof AuthApiAuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/teachers/add': {
      id: '/_auth/admin/teachers/add'
      path: '/teachers/add'
      fullPath: '/admin/teachers/add'
      preLoaderRoute: typeof AuthAdminTeachersAddRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/students/add': {
      id: '/_auth/admin/students/add'
      path: '/students/add'
      fullPath: '/admin/students/add'
      preLoaderRoute: typeof AuthAdminStudentsAddRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/students/$studentId': {
      id: '/_auth/admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/grades/$name': {
      id: '/_auth/admin/grades/$name'
      path: '/grades/$name'
      fullPath: '/admin/grades/$name'
      preLoaderRoute: typeof AuthAdminGradesNameRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/announcements/$announcementTitleSlug': {
      id: '/_auth/admin/announcements/$announcementTitleSlug'
      path: '/announcements/$announcementTitleSlug'
      fullPath: '/admin/announcements/$announcementTitleSlug'
      preLoaderRoute: typeof AuthAdminAnnouncementsAnnouncementTitleSlugRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/teachers/$teacherId/': {
      id: '/_auth/admin/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId/'
      preLoaderRoute: typeof AuthAdminTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/teachers/$teacherId/assignements': {
      id: '/_auth/admin/teachers/$teacherId/assignements'
      path: '/teachers/$teacherId/assignements'
      fullPath: '/admin/teachers/$teacherId/assignements'
      preLoaderRoute: typeof AuthAdminTeachersTeacherIdAssignementsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminCalendarRoute: typeof AuthAdminCalendarRoute
  AuthAdminCreateAnnouncementRoute: typeof AuthAdminCreateAnnouncementRoute
  AuthAdminDashboardRoute: typeof AuthAdminDashboardRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminAnnouncementsAnnouncementTitleSlugRoute: typeof AuthAdminAnnouncementsAnnouncementTitleSlugRoute
  AuthAdminGradesNameRoute: typeof AuthAdminGradesNameRoute
  AuthAdminStudentsStudentIdRoute: typeof AuthAdminStudentsStudentIdRoute
  AuthAdminStudentsAddRoute: typeof AuthAdminStudentsAddRoute
  AuthAdminTeachersAddRoute: typeof AuthAdminTeachersAddRoute
  AuthAdminAnnouncementsIndexRoute: typeof AuthAdminAnnouncementsIndexRoute
  AuthAdminGradesIndexRoute: typeof AuthAdminGradesIndexRoute
  AuthAdminStudentsIndexRoute: typeof AuthAdminStudentsIndexRoute
  AuthAdminTeachersIndexRoute: typeof AuthAdminTeachersIndexRoute
  AuthAdminTeachersTeacherIdAssignementsRoute: typeof AuthAdminTeachersTeacherIdAssignementsRoute
  AuthAdminTeachersTeacherIdIndexRoute: typeof AuthAdminTeachersTeacherIdIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminCalendarRoute: AuthAdminCalendarRoute,
  AuthAdminCreateAnnouncementRoute: AuthAdminCreateAnnouncementRoute,
  AuthAdminDashboardRoute: AuthAdminDashboardRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminAnnouncementsAnnouncementTitleSlugRoute:
    AuthAdminAnnouncementsAnnouncementTitleSlugRoute,
  AuthAdminGradesNameRoute: AuthAdminGradesNameRoute,
  AuthAdminStudentsStudentIdRoute: AuthAdminStudentsStudentIdRoute,
  AuthAdminStudentsAddRoute: AuthAdminStudentsAddRoute,
  AuthAdminTeachersAddRoute: AuthAdminTeachersAddRoute,
  AuthAdminAnnouncementsIndexRoute: AuthAdminAnnouncementsIndexRoute,
  AuthAdminGradesIndexRoute: AuthAdminGradesIndexRoute,
  AuthAdminStudentsIndexRoute: AuthAdminStudentsIndexRoute,
  AuthAdminTeachersIndexRoute: AuthAdminTeachersIndexRoute,
  AuthAdminTeachersTeacherIdAssignementsRoute:
    AuthAdminTeachersTeacherIdAssignementsRoute,
  AuthAdminTeachersTeacherIdIndexRoute: AuthAdminTeachersTeacherIdIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthStudentRouteChildren {
  AuthStudentCalendarRoute: typeof AuthStudentCalendarRoute
  AuthStudentSettingsRoute: typeof AuthStudentSettingsRoute
  AuthStudentAnnouncementsAnnouncementTitleSlugRoute: typeof AuthStudentAnnouncementsAnnouncementTitleSlugRoute
  AuthStudentSubjectsSubjectCodeRoute: typeof AuthStudentSubjectsSubjectCodeRoute
  AuthStudentAnnouncementsIndexRoute: typeof AuthStudentAnnouncementsIndexRoute
  AuthStudentSubjectsIndexRoute: typeof AuthStudentSubjectsIndexRoute
}

const AuthStudentRouteChildren: AuthStudentRouteChildren = {
  AuthStudentCalendarRoute: AuthStudentCalendarRoute,
  AuthStudentSettingsRoute: AuthStudentSettingsRoute,
  AuthStudentAnnouncementsAnnouncementTitleSlugRoute:
    AuthStudentAnnouncementsAnnouncementTitleSlugRoute,
  AuthStudentSubjectsSubjectCodeRoute: AuthStudentSubjectsSubjectCodeRoute,
  AuthStudentAnnouncementsIndexRoute: AuthStudentAnnouncementsIndexRoute,
  AuthStudentSubjectsIndexRoute: AuthStudentSubjectsIndexRoute,
}

const AuthStudentRouteWithChildren = AuthStudentRoute._addFileChildren(
  AuthStudentRouteChildren,
)

interface AuthTeacherRouteChildren {
  AuthTeacherCalendarRoute: typeof AuthTeacherCalendarRoute
  AuthTeacherCreateAnnouncementRoute: typeof AuthTeacherCreateAnnouncementRoute
  AuthTeacherSettingsRoute: typeof AuthTeacherSettingsRoute
  AuthTeacherAnnouncementsAnnouncementTitleSlugRoute: typeof AuthTeacherAnnouncementsAnnouncementTitleSlugRoute
  AuthTeacherClassesClassIdRoute: typeof AuthTeacherClassesClassIdRoute
  AuthTeacherMarksClassIdRoute: typeof AuthTeacherMarksClassIdRoute
  AuthTeacherSubjectsSubjectCodeRoute: typeof AuthTeacherSubjectsSubjectCodeRoute
  AuthTeacherAnnouncementsIndexRoute: typeof AuthTeacherAnnouncementsIndexRoute
  AuthTeacherClassesIndexRoute: typeof AuthTeacherClassesIndexRoute
  AuthTeacherSubjectsIndexRoute: typeof AuthTeacherSubjectsIndexRoute
}

const AuthTeacherRouteChildren: AuthTeacherRouteChildren = {
  AuthTeacherCalendarRoute: AuthTeacherCalendarRoute,
  AuthTeacherCreateAnnouncementRoute: AuthTeacherCreateAnnouncementRoute,
  AuthTeacherSettingsRoute: AuthTeacherSettingsRoute,
  AuthTeacherAnnouncementsAnnouncementTitleSlugRoute:
    AuthTeacherAnnouncementsAnnouncementTitleSlugRoute,
  AuthTeacherClassesClassIdRoute: AuthTeacherClassesClassIdRoute,
  AuthTeacherMarksClassIdRoute: AuthTeacherMarksClassIdRoute,
  AuthTeacherSubjectsSubjectCodeRoute: AuthTeacherSubjectsSubjectCodeRoute,
  AuthTeacherAnnouncementsIndexRoute: AuthTeacherAnnouncementsIndexRoute,
  AuthTeacherClassesIndexRoute: AuthTeacherClassesIndexRoute,
  AuthTeacherSubjectsIndexRoute: AuthTeacherSubjectsIndexRoute,
}

const AuthTeacherRouteWithChildren = AuthTeacherRoute._addFileChildren(
  AuthTeacherRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRouteWithChildren
  AuthTeacherRoute: typeof AuthTeacherRouteWithChildren
  AuthApiAuthSplatRoute: typeof AuthApiAuthSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthStudentRoute: AuthStudentRouteWithChildren,
  AuthTeacherRoute: AuthTeacherRouteWithChildren,
  AuthApiAuthSplatRoute: AuthApiAuthSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LogInRoute: LogInRoute,
  SignUpRoute: SignUpRoute,
  PagesAboutRoute: PagesAboutRoute,
  PagesBlogRoute: PagesBlogRoute,
  PagesCareersRoute: PagesCareersRoute,
  PagesChangelogRoute: PagesChangelogRoute,
  PagesCommunityRoute: PagesCommunityRoute,
  PagesCookiePolicyRoute: PagesCookiePolicyRoute,
  PagesDocumentationRoute: PagesDocumentationRoute,
  PagesHelpRoute: PagesHelpRoute,
  PagesLicensesRoute: PagesLicensesRoute,
  PagesPressRoute: PagesPressRoute,
  PagesPricingRoute: PagesPricingRoute,
  PagesPrivacyRoute: PagesPrivacyRoute,
  PagesSecurityRoute: PagesSecurityRoute,
  PagesTermsRoute: PagesTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
